services:
  planimport-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3200:3200"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  planimport-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4300:80"
    depends_on:
      - planimport-backend
    restart: unless-stopped
